plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md

show_downloads: true
title: BigQuery Grafana
description: BigQuery Datasource for Grafana
google_analytics:  UA-137158105-1
theme: jekyll-theme-midnight
