version: 2.1
  - codecov/upload:
      token: a1127a6b-ce13-4174-9d14-6dbfa7252a54


orbs:
  codecov: codecov/codecov@1.0.4
  jobs:
    build:
      steps:

jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: install yarn
          command: 'sudo npm install -g yarn --quiet'
      - run:
          name: yarn install
          command: 'yarn install --pure-lockfile --no-progress'
      - run:
          name: test
          command: 'yarn test'
      - run:
          name: build
          command: 'run build:prod'
      - codecov/upload:
          file: coverage/*.json
      - store_artifacts:
          path: dist
